
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package py1_201603028;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int mayorq = 17;
  public static final int llave_c = 10;
  public static final int ERROR = 18;
  public static final int llave_a = 9;
  public static final int c_Especial = 14;
  public static final int dos_puntos = 3;
  public static final int menos = 16;
  public static final int punto = 4;
  public static final int c_ERegular = 13;
  public static final int interrogante = 8;
  public static final int EOF = 0;
  public static final int id = 11;
  public static final int id_ERegular = 12;
  public static final int error = 1;
  public static final int pipe = 7;
  public static final int reservada = 2;
  public static final int asterisco = 6;
  public static final int mas = 5;
  public static final int punto_coma = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "reservada",
  "dos_puntos",
  "punto",
  "mas",
  "asterisco",
  "pipe",
  "interrogante",
  "llave_a",
  "llave_c",
  "id",
  "id_ERegular",
  "c_ERegular",
  "c_Especial",
  "punto_coma",
  "menos",
  "mayorq",
  "ERROR"
  };
}

